name: Lambda Function Deploy CI/CD

on:
  push:
    paths:
      - "src/*"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print job name
        run: echo "Deploying Lambda's code"
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create Zip file for lambda function
        run: cd src && zip -r code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with: 
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:520623607713:function:TestCICDFunction \
            --zip-file fileb://src/code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: "us-east-1"